### ISSUE TITLE
Component should error when missing required variable

### ISSUE THREAD

**Issue by vinyldarkscratch** [devrnt/react-use-intercom#11]
My employer had seen a post for this on `react-intercom` and decided to give it a shot.  Glad to see someone with an actively-maintained project for this!  However, I ran into a slight issue during my migration.  I couldn't figure out why for the longest time...until I realized that I was using a capital "D" in "appId", rather than a lowercase one.  It would have helped to have been alerted that app ID is missing.

**Comment by devrnt** [comment]
@vinyldarkscratch Thanks for your suggestion. I'll definitely integrate your request in the next version. 

I would suggest to make use of the out of the box autocompletion :). Or migrate to TypeScript, this 
kind of problem would give you a compilation error when you're not using the correct properties.

**Comment by vinyldarkscratch** [comment]
Awesome, thank you!  A migration to TypeScript will be most likely impossible for the size of the project, but I'll be sure to pass along the idea of the autocompletion.  :)

P.S. you'll probably be seeing some PRs coming your way soon from yours truly!
