### ISSUE TITLE
Error with jsdom & jest: "TypeError: Cannot read property '_ownerDocument' of undefined"

### ISSUE THREAD

**Issue by davidkaneda** [devrnt/react-use-intercom#119]
**Describe the bug**
I'm getting the following error using Jest (^26.6.1): 

```
  ● Title

    TypeError: Cannot read property '_ownerDocument' of undefined

      at innerInvokeEventListeners (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:327:26)
      at invokeEventListeners (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:274:3)
      at EventTargetImpl._dispatch (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:221:9)
      at fireAnEvent (node_modules/jsdom/lib/jsdom/living/helpers/events.js:18:36)
      at node_modules/jsdom/lib/jsdom/browser/Window.js:773:7
```

Here's the test file:

```javascript
import { render } from "@testing-library/react"; // ^11.1.0
import React from "react"; // 16.14.0
import { IntercomProvider } from "react-use-intercom"; // ^1.1.2

class MyComponent extends React.Component {
  render() {
    return (<IntercomProvider appId="123">Hello</IntercomProvider>);
  }
}

test("Title", async function () {
  const { findByText } = render(<MyComponent />);
  expect(await findByText("Hello")).toBeVisible();
});
```

For now I can get around it by mocking `react-use-intercom`, but thought you might want to be aware. Code works fine in actual app, pretty sure this is just some wonkiness in jsdom.

**Comment by devrnt** [comment]
Thanks for your report @davidkaneda ! A quick search says the best way to "solve" this is to mock it (like you do). 

I'll have a look at it this weekend.

**Comment by devrnt** [comment]
Using `getByText` "fixes" this issue. Don't know what the reason is that it fails with the async variant of `getByText` (the one that you were using `findByText`).

I state the `@testing-library` docs:

> `findByText` is a simple combination of getBy* queries and waitFor. The findBy* queries accept the waitFor options as the last argument. (i.e. screen.findByText('text', queryOptions, waitForOptions))

So something is off with the `waitFor` in this use case, don't know if playing around with the `waitForOptions` could fix your issue here.
