### ISSUE TITLE
Gatsby support?

### ISSUE THREAD

**Issue by bneigher** [devrnt/react-use-intercom#141]
**Is your feature request related to a problem? Please describe.**
I'm trying to use this in my application - but not having any success..  I'm definitely passing in everything I need to be, and the library is functioning (I can see warnings for improper usage (show before boot, ect.)).

However I think there is something wrong with the window.Intercom bit, as I don't see any communication with intercom's apis running.  

I'm a little sus that my problem is because I'm using gatsby (does some fancy footwork when running and building my app that could be dicking around with some window / global hooha. 

**Describe the solution you'd like**
Has anyone verified that this works with a gatsby react app? (no SSR).  If this doesn't work with gatsby - that would be an awesome enhancement.

**Describe alternatives you've considered**
I've tried creating a single file HOC which lives pretty high up in my app, all the way to putting the loading and booting logic in a UI component.

**Additional context**
React ^17,
Gatsby ^2.27.0

Happy to share the HOC I made.  In short - its a reactive component that boots when a property in the auth store changes (user id exists or becomes null [log in condition / log out condition]) or when the app first starts (b/c useEffect)

```javascript
import React, { useEffect } from 'react'
import * as actions from 'actions'
import { connect } from 'react-redux'
import { compose } from 'recompose'
import { IntercomProvider, useIntercom } from 'react-use-intercom';

const IntercomAuthResponder = ({ auth, children }) => {
  const { boot, shutdown } = useIntercom();
  const bootWithProps = React.useCallback(() => boot({ 
    userId: auth.sub,
    email: auth.email
  }), [boot]);
  useEffect(() => {   
    if (auth.sub) { 
      console.log('regular boot');
      bootWithProps()
    } else {
      console.log('shttting down');
      shutdown()
    }
  }, [auth.sub])
  
  return (<>{children}</>)
}

const IntercomBootMasterComponent = (props) => {
  const onHide = React.useCallback(
    () => console.log('Intercom did hide the Messenger'),
    [],
  );
  const onShow = React.useCallback(
    () => console.log('Intercom did show the Messenger'),
    [],
  );

  return (
    <IntercomProvider appId={process.env.INTERCOM_APP_ID} onHide={onHide} onShow={onShow}>
      <IntercomAuthResponder auth={props.auth}>
        {props.children}
      </IntercomAuthResponder>
    </IntercomProvider>
  )
}

const mapStateToProps = ({ auth }) => {
	return {
		auth,
	}
}

export default compose(connect(mapStateToProps, actions))(IntercomBootMasterComponent)
```

**Comment by devrnt** [comment]
Awesome, thanks for the detailed issue report! Really appreciate it 👌
 
I think `gatsby-browser.js` is exactly what you need. I did following to get this to work:

Add following to `gatsby-browser.js`, more info: https://www.gatsbyjs.com/docs/api-files-gatsby-browser/
```jsx
import React from 'react';
import { IntercomProvider } from 'react-use-intercom';

export const wrapRootElement = ({ element }) => (
  <IntercomProvider appId="[YOUR_APP_ID]">
    {element}
  </IntercomProvider>
);
```
A restart of your gatsby dev environment is needed since `gatsby-browser` changed. As of now you can invoke `useIntercom` anywhere in your app.

Hope this help!

**Comment by bneigher** [comment]
@devrnt Indeed that is where my HOC `IntercomBootMasterComponent` lives.  Here is my gatsby-browser.js:

```javascript
import React from 'react'
import { Provider } from 'react-redux'
import * as types from 'action_types'
import { PersistGate } from 'redux-persist/integration/react'
import { configuredStore } from 'src/configureStore'
import i18next from 'src/locales/i18next'
import { SnackbarProvider } from 'notistack'
import { I18nextProvider } from 'react-i18next'
import ThemeProvider from './wrap-with-context'
import CalendarProvider from './src/utils/CalendarProvider'
import { SnackbarUtilsConfigurator } from './src/utils/SnackbarUtils'
import IntercomBootMasterComponent from './src/utils/IntercomBootMaster'

import 'src/styles' // global styles

export const wrapRootElement = ({ element }) => {
  return (
    <Provider store={configuredStore.store}>
      <PersistGate loading={null} persistor={configuredStore.persistor} onBeforeLift={() => {}}>
        <IntercomBootMasterComponent> /* Here is Intercom */
          <I18nextProvider i18n={i18next}>
            <CalendarProvider>
              <ThemeProvider>
                <SnackbarProvider maxSnack={3}>  
                  <SnackbarUtilsConfigurator />
                  {element}
                </SnackbarProvider>
              </ThemeProvider>
            </CalendarProvider>
          </I18nextProvider>
        </IntercomBootMasterComponent>
      </PersistGate>
    </Provider>
  )
}

export const onRouteUpdate = ({ location, prevLocation }) => {
  configuredStore.store.dispatch({ type: types.SCENE, payload: location.pathname })
}
```

I can try testing a more simple gatsby app example.  Perhaps the issue is with some other HOC... but I don't see why that would happen.  Will keep digging 🔍

**Comment by devrnt** [comment]
@bneigher I'll leave this issue open for know, just post an update to this ticket if you have an update. I hope you find a solution!

**Comment by devrnt** [comment]
@bneigher Any updates regarding this issue? Otherwise I'll close this issue for know, can always be reopened.

**Comment by bneigher** [comment]
@devrnt Go ahead and close it, haven't had time to figure this out. Thanks for being on top of your issues page - you're doing open source like a champ!
