### ISSUE TITLE
Expose isBooted in useIntercomContext

### ISSUE THREAD

**Issue by chillyistkult** [devrnt/react-use-intercom#149]
**Is your feature request related to a problem? Please describe.**
Sometimes you only want to show Intercom to specific users. In this case Intercom is booted conditionally. There is almost always some code that runs regardless if Intercom is booted or not, such as calling update in a Single Page Application to update Intercom with the current URL. In this scenario I would need to check myself if Intercom is booted or not to not trigger your warnings, but it would be better if I could just reuse `isBooted` from within `IntercomProvider`.

**Describe the solution you'd like**
Expose `isBooted` as a context value.

**Describe alternatives you've considered**
Provide an option to disable warnings in dev mode. In my scenario I intentionally call update to refresh the URL in Intercom even if I know Intercom is not booted (for specific types of users). You handle this case well, but I don't want to get spammed by warnings.

**Comment by devrnt** [comment]
Hi thanks for creating this issue. Exposing `isBooted` should be relatively simple, but since refs are used to avoid re-renders I'll have to take a quick look into it (don't want to use `useState`).

I don't think making it possible to hide warnings is a good idea as they offer added value for the developer. They are there to raise awareness of certain conveniences. These warnings are only in the development bundle as well.

Feel free to add comments to this issue

**Comment by chillyistkult** [comment]
I agree exposing isBooted would probably do the job.

**Comment by devrnt** [comment]
Is watching over the "current" user and then call either `boot` or `shutdown` a possible solution?

**Comment by chillyistkult** [comment]
> Is watching over the "current" user and then call either `boot` or `shutdown` a possible solution? And ignore the warnings (if they occur)

At the moment based on certain user criteria I either boot intercom or do nothing, but shutting down intercom if this criteria is not met also requires me to know if it was booted before. Of course I could just ignore the warnings and be fine with it, but I think letting a developer know if intercom is booted or not is certainly a good thing and would allow for a more robust implementation.

**Comment by devrnt** [comment]
I certainly agree, but since this would require the use of `useState` it would mean that the "zero re-render" isn't true anymore. It's kind of a dilemma, I'll pick this up again asap. 

You're free to make a PR with another approach, but atm I only way to me seems using `useState`.

**Comment by devrnt** [comment]
I've got 2 proposals ready:

1) `useBooted` [example](https://github.com/devrnt/react-use-intercom/blob/feat/is-booted/proposal-1/example/modules/useIntercom/useIntercom.tsx#L37)


###### **TLDR:**
Get `useBoot` from `useIntercom` and call `useBoot` with as argument `React.useState(false)`:

```js
const { useBooted } from useIntercom();

const isBooted = useBooted(React.useState(false));
```

2) `handleIsBooted` [example](https://github.com/devrnt/react-use-intercom/blob/feat/is-booted/proposal-2/example/modules/useIntercom/useIntercom.tsx#L37)

###### **TLDR:**
```js
const { handleIsBooted } from useIntercom();

const [isBooted, setIsBooted] = React.useState(false);

handleIsBooted(setIsBooted);
```

Both proposals are a workaround and make sure the `IntercomProvider` does not re-render.

**Comment by chillyistkult** [comment]
I thought about using `window.Intercom.booted` property. But it looks like its already `true` when Intercom got initialized. Need to investigate a bit further. I think the solutions you mentioned are just too weird to pollute an otherwise great library.

**Comment by devrnt** [comment]
The `window.Intercom.booted` isn't an option, I considered to use it as well, but had the same observation. Another approach would be to create an event and dispatch it whenever `isBooted` is changed. You would pass a callback to `IntercomProvider` so you can keep track of the state by yourself.

**Comment by devrnt** [comment]
@chillyistkult Any updates regards this topic? Otherwise I'll close it for now if it has been solved.

**Comment by chillyistkult** [comment]
@devrnt Hey sorry forgot to follow up on this one. I implemented a workaround on my side and track the booted state myself, so I will close it. Thank you for your help.

**Comment by marcvangend** [comment]
3 years have passed, so obviously this is not very high on everybody's wish list... But I do want to mention that I came to the docs today looking for exactly this. Unfortunately the proposals from https://github.com/devrnt/react-use-intercom/issues/149#issuecomment-738207869 have gone and the workaround by the OP has not been shared. Any help is appreciated.
