### ISSUE TITLE
Positioning the Intercom button

### ISSUE THREAD

**Issue by brennanfife** [devrnt/react-use-intercom#151]
I am currently building out a navbar for an application. However, the intercom button, which fits perfectly on desktop, covers the mobile navbar (fixed to the bottom of the screen). Is there anyway I can target the position of the intercom button, possibly just to lift it up a couple dozen pixels?

**Comment by brennanfife** [comment]
Hmm, I am able to modify the position (with right or left alignment as well as vertical and horizontal padding) within desktop view, but am not on mobile (can only control left or right alignment)? Any idea how i might get around this?

**Comment by devrnt** [comment]
Reading the Intercom attributes https://developers.intercom.com/installing-intercom/docs/javascript-api-attributes-objects#section-messenger-attributes says that vertical padding isn't supported on mobile.

You'll need to do some manual work: https://www.intercom.com/help/en/articles/2894-customize-the-intercom-messenger-technical

You'll need to set `customLauncherSelector` in the `boot` or `update` method.
