### ISSUE TITLE
How would you go about hiding/showing the launcher?

### ISSUE THREAD

**Issue by xlozinguez** [devrnt/react-use-intercom#159]
**Is your feature request related to a problem? Please describe.**
We have UX in our app that requires us to disable the launcher and shutting down Intercom seems a bit heavy handed. I'm concerned of the impact it has on user authentication when using `shutdown`. 

**Describe the solution you'd like**
A simple way to toggle `display: none` on the intercom launcher could do the trick. Ideally this could be a feature of this lib.

**Describe alternatives you've considered**
I have tried using `shutdown` when on the specific UX in something like:
```
const { shutdown, boot } = useIntercom()
useEffectOnce(() => {
  shutdown()
  // Restore Intercom modal once the page is closed
  return () => boot()
})
```

But the messenger does not reappear :/

**Additional context**

**Comment by devrnt** [comment]
Hi, thanks for creating this issue! 

You are looking for `hideDefaultLauncher`, you can set this in both the `boot` and `update` method. Checkout [this](https://github.com/devrnt/react-use-intercom/blob/master/src/types.ts#L42) for more info.  


You should use it like this:
```js
update({ hideDefaultLauncher: isMessengerVisible })
```

Hope it solves your issue 🤞

**Comment by xlozinguez** [comment]
Thanks a lot for the tip @devrnt , worked like a charm! 🎉
