### ISSUE TITLE
Bug: custom variables do not work

### ISSUE THREAD

**Issue by vinyldarkscratch** [devrnt/react-use-intercom#17]
It appears that custom variables passed to Intercom don't work, potentially due to the same function that affects #16.  My employer and I were playing around with the custom variables, but none of them were sent to Intercom.  (We confirmed that setting a name worked, however.)

I will most likely be writing a PR to fix both of these issues!

**Comment by devrnt** [comment]
Thanks for reporting. This is indeed a confirmed issue. I'll try to release a new version with a fix for this at the end of the week.

I was thinking about auto converting custom attributes from camel cased to pascal cased. At this moment it seemed more convenient to let these custom attributes in their raw state.

Thanks for helping!

**Comment by vinyldarkscratch** [comment]
Automatic camel-snake conversion sounds like a good way to go about it, yeah!  I'm working on a little something right now to help with this.  (One of the downsides will be that custom variables that are supposed to be camel-cased will be converted...  Maybe an option is to have some sort of "customVars" object?)

**Comment by devrnt** [comment]
Intercom likes their variables pascal cased, so I would suggest to just keep it that way. If auto conversion would be implemented, all the camel cased variables would be converted to pascal casing (just one way).

**Comment by vinyldarkscratch** [comment]
Ah, looks like I had partially misread your last message -- I sort of skimmed through it, whoops...  When I read it, I thought you were talking about having automatic conversion for camel casing and snake casing (nothing to do with pascal casing) for all of the variables involved, rather than just custom variables.

Actually, for our setup, we use snake-cased variable names rather than pascal-cased ones, and it's highly probable that others may do the same (or use other case styles).  As such, I think it'd be best not to tamper with the case style of any custom variables, only the Intercom native props.

**Comment by devrnt** [comment]
Just made an edit to my previous comment (snake cased instead of pascal cased).

It makes sense to my to provide `react-use-intercom` as JavaScript/TypeScript "friendly" as possible, I will make it more clearly that the attributes from the Intercom docs are typed camel case.

If the user would like to use custom_attributes they still have to pass the snake cased attributes.
