### ISSUE TITLE
Is it possible to boot up only the Intercom messanger?

### ISSUE THREAD

**Issue by brennanfife** [devrnt/react-use-intercom#189]
Hello,

Is it possible to open the Intercom messenger without the Intercom Icon. I've see a few sites, upon request helping, boots up Intercom without the Intercom Icon. Take for example [dYdX](https://trade.dydx.exchange/margin/ETH-DAI). If you click on the Help Chat icon in the upper left corner, it opens the Intercom messenger without the Intercom icon.

**Comment by devrnt** [comment]
Hi, thanks for creating this issue. 

Yes there is you can set `hideDefaultLauncher` to `false` in both the `boot` and `update` function from `useIntercom`.

**Comment by brennanfife** [comment]
Awesome, that worked! Thanks for the help 👍!
