### ISSUE TITLE
Hide Live Chat Window

### ISSUE THREAD

**Issue by shane-arthur** [devrnt/react-use-intercom#196]
Is there a way to hide the live chat window, so once booted, new messages in app don't implicitly open the transparent live chat window?

**Comment by devrnt** [comment]
Thanks for creating this issue. This is totally up to Intercom. If you are not able to find any option [here](https://developers.intercom.com/installing-intercom/docs/javascript-api-attributes-objects) or you can't change it in the Intercom settings panel then this will unfortunately not be possible.
