### ISSUE TITLE
Add support for delaying the intercom initialize script to avoid performance issues

### ISSUE THREAD

**Issue by Siggnja** [devrnt/react-use-intercom#237]
**Is your feature request related to a problem? Please describe.**
We have an application that is optimized for performance and initializing the intercom script immediately on load is hurting it. I suggest to add a prop which can be used to delay the intercom initialization.

**Describe the solution you'd like**
See #236

**Comment by devrnt** [comment]
Hi Sigurður! Thanks for your submission, really appreciate it.

Could you elaborate on what you mean exactly by "hurting on load"? Anyway, as far I can see you should be good with `shouldInitialize`. I would move the timeout to the component where you use `IntercomProvider` and add a timeout right there. 

Something like:
```jsx
const App = () => {
  const [shouldInitialize, setShouldinitialize] = React.useState(false);

  React.useEffect(() => {
    const timer = setTimeout(() => {
      setShouldinitialize(true);
    }, 1000);

    return () => clearTimeout(timer);
  }, []);

  return (
    <IntercomProvider appId="APP_ID" shouldInitialize={shouldInitialize}>
      <p>Hi there</p>
    </IntercomProvider>
  );
};
```

Keep me updated if you're having any problems

**Comment by Siggnja** [comment]
@devrnt The intercom script adds around 100KB to the initial loads which slows down metric like First input delay and Largest content ful paint which are apart of the core web vital.

This implementation was taken directly form the intercom forum:
https://forum.intercom.com/s/question/0D52G00004WxWLs/can-i-delay-loading-intercom-on-my-site-to-reduce-the-js-load

It would be pretty nice to have this included in the library so that each person doesn't have to implement that snippet you posted above.

**Comment by devrnt** [comment]
After looking at this, as far as I can see there are no real side effects except for the fact that no functionality will work while the timeout is running

**Comment by devrnt** [comment]
Closed in https://github.com/devrnt/react-use-intercom/pull/236
