### ISSUE TITLE
The boot is not rendering

### ISSUE THREAD

**Issue by VanessaCarpes** [devrnt/react-use-intercom#291]
I've followed all the steps to use the boot but it is not rendering on the page.
If I inspect the page elements there are components instanced.

**To Reproduce**
- Include "IntercomProvider appId={INTERCOM_APP_ID} shouldInitialize"
- Call boot inside the page

**Codesandbox link**
(Just replace the APP ID)
https://codesandbox.io/s/blissful-lalande-2v5js?file=/src/index.js
https://codesandbox.io/s/gallant-fast-ufxrp?file=/src/App.js

**Expected behavior**
It was expected to render the icon to initiate a chat.

**Comment by devrnt** [comment]
Hi Vanessa, thanks for creating this issue. 

Following the codesandbox it seems to work for me. Are you sure that you're using a valid Intercom app-id? Can you checkout the console for any logs, while there could you checkout the network tab as well?

Make sure that your domain is whitelisted in the Intercom panel as well: https://www.intercom.com/help/en/articles/4418-list-trusted-domains-you-use-with-intercom

**Comment by VanessaCarpes** [comment]
Hi, Thanks a lot for your explanation.
I tried to use the APP ID you have in your codesandbox example and it worked fine.
I'm in touch with intercom to understand why my APP ID is not working.
