### ISSUE TITLE
Intercom launcher icon is disappearing after I call `update` method

### ISSUE THREAD

**Issue by davidli108** [devrnt/react-use-intercom#295]
**Describe the bug**
In login page, `boot` is called and it works successfully.
Then after a user is logged in, `update` is called with some intercomProps. But the intercom launcher is disappearing immediately.

here are some code snippets

// App.tsx
```
  <IntercomProvider appId={INTERCOM_APP_ID} shouldInitialize={true}>
    <GlobalStyles />
    <Router history={history}>{renderRoutes(routes)}</Router>
  </IntercomProvider>
```

```
  useEffect(() => {
    const { userData } = data
    const first_name = userData?.first_name || ''
    const last_name = userData?.last_name || ''
    setFullname(first_name + ' ' + last_name)

    if (isAuthenticated) {
      const interProps = {
        email: userData?.email,
        name: userData?.first_name + ' ' + userData?.last_name,
        createdAt: userData?.created_at
      } as IntercomProps

      boot(interProps)

      if (userData) {
        update(interProps) <====== **launcher icon is disappeared here,**
      }
    } else {
      boot()
    }
  }, [data, isAuthenticated, boot, update])
```

**Screenshots**
![image](https://user-images.githubusercontent.com/72030825/125739210-d22c198a-1bd3-4f30-ab9c-cdb36b724431.png)

**Additional context**

**Comment by devrnt** [comment]
Hi, thanks for creating this issue. However, I tried to replicate this but it seems to work as expected. Could you provide a codesandbox?

**Comment by davidli108** [comment]
Hi Jonas,

Thanks for your reply.
I created a codesandbox. 
https://codesandbox.io/s/distracted-gareth-b5duw?file=/src/index.js

Please check.
Thank you!

**Comment by devrnt** [comment]
This is strange, I'm having the same issue as you have, but I used another intercom app id and it does work like expected. Are you sure that this is not something that was set up in the Intercom panel?

**Comment by davidli108** [comment]
YEs, Jonas, It was my fault in the configuration of intercom.

Thanks for your time!!

**Comment by ahmad-reza619** [comment]
> YEs, Jonas, It was my fault in the configuration of intercom.
> 
> Thanks for your time!!

hello, i got the same problem, can you kindly describe how you solved the issue @davidli108 ?
