### ISSUE TITLE
How to "update" customAttributes on Intercom Button click?

### ISSUE THREAD

**Issue by awitherow** [devrnt/react-use-intercom#296]
When I click on the Intercom Button that is provided by the IntercomProvider, there does not seem to be a way to pass in customAttributes to that click.

Since the update function exposed by useIntercom cannot be called in the same component, only the child component of the Provider component, I am unsure how this would be possible.

I was hoping to do something similar to this...

```javascript
const ChatProvider = ({ setCustomAttributes } ) => {
  const { show, update } = useIntercom();

  const handleOpenIntercom = ({ ...props }) => {   
    // update custom attributes via this update function programatically
    update({
      customAttributes: {
        ...props
      },
    });
    show();
  };

  return <App handleOpenIntercom={handleOpenIntercom} setCustomAttributes={setCustomAttributes} />;
};

const ChatEnhancedBookingContainer = () => {
  const [customAttributes, setCustomAttributes] = useState()
  return (
    <IntercomProvider appId="" autoBoot customAttributes={customAttributes}>
      <ChatProvider setCustomAttributes={setCustomAttributes}/>
    </IntercomProvider>
  )
};
```

I am not sure if this makes sense or is the best solution.

Looking forward to hearing from you @devrnt 

Austin

**Comment by devrnt** [comment]
Hi Austin, I'm not entirely sure what you're trying to achieve (can't tell from your code snippet). But both `boot` and `update` can be called with `customAttributes`, what you send and where you retrieve these from is totally up to you

**Comment by awitherow** [comment]
I realised this after I had already written this ticket 🙃 thank you for responding!
