### ISSUE TITLE
Feature request: `autoBootOptions`

### ISSUE THREAD

**Issue by Tobbe** [devrnt/react-use-intercom#297]
**Is your feature request related to a problem? Please describe.**

I want to autoboot intercom, but in a hidden state

**Describe the solution you'd like**

```jsx
<IntercomProvider appId="abc123" autoBoot autoBootOptions={{ hideDefaultLauncher: true }}>
  // ...
</IntercomProvider>
```

**Describe alternatives you've considered**

Manually call `boot({ hideDefaultLauncher: true })`

**Additional context**

Manually calling `boot` obviously works, but we have no good place to do it, so we end up having to have that call in a bunch of different places, which makes it more likely we'll eventually forget if we add another entrypoint to our app.

**Comment by devrnt** [comment]
Hi, thanks for creating this feature request. It seems very do-able. Will take a look at it once I've more time, but pull requests are certainly welcome 😉
