### ISSUE TITLE
Don't require `appId`

### ISSUE THREAD

**Issue by aaronadamsCA** [devrnt/react-use-intercom#351]
**Is your feature request related to a problem? Please describe.**
We use Segment to externally boot Intercom, and as such we'll never use this library to boot. As far as I can tell, this is the only situation where `appId` is needed, yet it's a required parameter.

**Describe the solution you'd like**
Make `appId` optional. `throw` if a user attempts to boot/autoboot Intercom without `appId`.

**Describe alternatives you've considered**
Pass a fake `appId` string.

**Comment by devrnt** [comment]
I'll close this issue for now. Feel free to re-open this if you want to discuss this further
