### ISSUE TITLE
onShow / onHide does not get called

### ISSUE THREAD

**Issue by nicoraynaud** [devrnt/react-use-intercom#361]
**Describe the bug**
Have integrated this plugin and everything is working correctly except for the onHide and onShow events that are not triggered.

**To Reproduce**
1. installed and used the hook to display Intercom properly.
2. i am showing/hiding intercom using a react state property that triggers the show/hide methods of userIntercom hook.
3. whenever i show or hide the module, onShow and onHide are not triggered
4. whenever i close the widget from within intercom (using the close button inside), the onHide callback does not get triggered

**Codesandbox link**
i have no sandbox code

**Expected behavior**
whenever we call close() or the user closes the widget from inside, the onHide should get triggered.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser Chromium/Firefox/Safari

**Smartphone (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by Seamus1989** [comment]
second that, it doesnt work. Set up is fine

**Comment by devrnt** [comment]
What's not working? Works like expected in the playground
