### ISSUE TITLE
Anyway this package can be lazy loaded?

### ISSUE THREAD

**Issue by brennanfife** [devrnt/react-use-intercom#364]
**Is your feature request related to a problem? Please describe.**
When running the performance option within Chrome's Lighthouse, one of the warnings that may be thrown notes: 'Some third-party resources can be lazy loaded with a facade'

<img width="444" alt="screen-shot" src="https://user-images.githubusercontent.com/31396350/139469822-32f908ad-af71-4282-8eaa-4ad80c808a09.png">

[After some googling](https://www.google.com/search?q=some+third-party+resources+can+be+lazy+loaded+with+a+facade+intercom&sxsrf=AOaemvKFkHim5opE7nLtw-vwuCCJ0lXdcA%3A1635524266542&ei=qh58YY6lIMenqtsPzMO1sAk&oq=some+third-party+resources+can+be+lazy+loaded+with+a+facade+intercom&gs_lcp=Cgdnd3Mtd2l6EAM6BwgjELADECc6BwgAEEcQsAM6BQgAEIAESgQIQRgAUPUWWMkhYKkkaAJwAngAgAGYAYgBiAeSAQM1LjSYAQCgAQHIAQnAAQE&sclient=gws-wiz&ved=0ahUKEwiOorbXgvDzAhXHk2oFHcxhDZYQ4dUDCA4&uact=5), the solution notes one should delay the loading of the third-party embeds and replace them with static elements until the user interacts with the component, in this case, an Intercom button. 

Now assuming the Intercom button boots on the initial render of the application, can we replace the element with something static until the user clicks the Intercom element?

**Comment by devrnt** [comment]
Hi, thank you for this issue.

Intercom provides some official docs to "lazy load" the scripts, see https://www.intercom.com/help/en/articles/5053693-can-i-delay-loading-intercom-on-my-site-to-reduce-the-js-load and https://forum.intercom.com/s/question/0D52G00004WxWLs/can-i-delay-loading-intercom-on-my-site-to-reduce-the-js-load.

To use it with `react-use-intercom`, see `initializeDelay` in https://github.com/devrnt/react-use-intercom#intercomprovider. You can find the PR of functionality [here](https://github.com/devrnt/react-use-intercom/pull/236)

**Comment by devrnt** [comment]
I'll close this issue for now. Feel free to re-open this if you want to discuss this further

**Comment by elliotaplant** [comment]
Thanks for solving the initial-load issue! I'd love to delay loading

> until the user interacts with the component

as @brennanfife put in their original post. Would you be open to a pull request where I add the ability to delay initialization until the user clicks a button and expose "initialized" and "booted" from the context?
