### ISSUE TITLE
withIntercom

### ISSUE THREAD

**Issue by jessejamesrich** [devrnt/react-use-intercom#368]
**Is your feature request related to a problem? Please describe.**
This would be a nice feature for existing frameworks that are using HOC. 

**Describe the solution you'd like**
Pretty self-explanatory

**Describe alternatives you've considered**
I have to alter the public/index.js and app.js, which isn't really great. 

**Additional context**
Thanks for this in any regard.

**Comment by devrnt** [comment]
Hi, thanks for this feature request, but this won't happen.

Some reasons: 
* The focus for this package is to only support React hooks, see the [minimum React version](https://github.com/devrnt/react-use-intercom/blob/master/package.json#L61) 
* Hence the name `react-use`**-intercom**
* ...
