### ISSUE TITLE
Question: Possibility to check if Intercom has been successfully loaded?

### ISSUE THREAD

**Issue by fhollste** [devrnt/react-use-intercom#378]
I have a custom launcher which I would like to hide if Intercom could not be initialized, eg. due to blocked script. Is there any method for checking this?

**Comment by devrnt** [comment]
Hi, at the moment this doesn't seem to be supported, but you could try asking it in the [Intercom forum](https://forum.intercom.com/s/).

Can you check what the value is of `window.Intercom`?

**Comment by devrnt** [comment]
Feel free to re-open if still have some questions
