### ISSUE TITLE
Dialog opening causes custom fonts re-render [Next.js]

### ISSUE THREAD

**Issue by AlexanderZanin** [devrnt/react-use-intercom#388]
**Describe the bug**
I use next.js and I want to add some non-system fonts.
Once I add the fonts AND `link rel="preload"` in the head to preload the fonts to avoid initial font flickering I get the font glitching after the intercom dialog opening. 

**To Reproduce**
1. Use default next.js bootstrap setup 
2. Add any custom font to a project (i.e. montserrat)
3. Add `link rel="preload"` to the head and specify path to custom fonts
4. install and configure react-use-intercom
5. boot intercom and open the dialog
6. Pay attention to the font on the page

**Expected behavior**
The font shouldn't be re-rendered

**Screenshots**

https://user-images.githubusercontent.com/10371454/147265924-0c655004-b790-4086-941f-18cbf0a53476.mov

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Chrome
 - Version 96

**Additional context**
`font-display` property doesn't help much either. The best solution I found is to use `font-display: fallback;` but the blank flickering is still present.

**Comment by devrnt** [comment]
Thanks for creating this issue. This doesn't seem something related to `react-use-intercom` (or in general for intercom).

However, I can take a quick look if you provide a reproduction (you can use https://stackblitz.com/). At the moment I've no idea how you use nextjs, css, load the font...

**Comment by AlexanderZanin** [comment]
@devrnt , thanks for the attention and quick response!
Hm, maybe you are right and this issue is related to the iframes and how preloaded fonts work with them. But anyway I don't understand why this is happening so I would really appreciate any help or hint. 

I'm not sure if I can use [https://stackblitz.com/](https://stackblitz.com/) since it doesn't support files uploading (I need to upload the fonts files) and if I use link to font's CDN I cannot reproduce the issue in stackblitz.

Would it be okay if I just push this example to GitHub so you can check it in the repository?
[https://github.com/AlexanderZanin/next-fonts](https://github.com/AlexanderZanin/next-fonts)
Sorry for inconvenience.

**Comment by devrnt** [comment]
I checked it out and it's indeed flickering. However, this seems not related to this package.

I suggest loading the fonts like mentioned in https://nextjs.org/docs/basic-features/font-optimization or via https://fontsource.org. I've tried both solutions and they work (without flickering)

Let me know if you need anything else
