### ISSUE TITLE
Provide style customization to the user

### ISSUE THREAD

**Issue by mmejiadeveloper** [devrnt/react-use-intercom#412]
**Itercom provide few style options that should be provided here as well**
If you look to these intercom [docs](https://www.intercom.com/help/en/articles/1118385-can-i-move-the-messenger-s-position-on-my-product-or-site) you will see that the window can be configured from admin dashboard but it can be configured from JS as well.

**How would i do?**
I would add something like
```tsx
<IntercomProvider
    autoBoot 
    styles={{ alignment: 'left',
      horizontal_padding: 20,
      vertical_padding: 20
    }} 
    appId={INTERCOM_APP_ID}>
```

**As workaround im being force to use the customer hook boot method to specify this **
What im currently doing:
```ts
const { boot, shutdown, hide, show, update } = useIntercom()

  return (
    <button
      onClick={() =>
        boot({
          alignment: 'left',
          horizontal_padding: 20,
          vertical_padding: 20
        })
      }
    >
      Boot intercom! ☎️
    </button>
  )
```

**Comment by devrnt** [comment]
Hi, you're looking for `autoBootProps`, see https://github.com/devrnt/react-use-intercom/blob/master/src/types.ts#L439.

Hope that solves your issue!
