### ISSUE TITLE
Cannot destructure property 'show' of 'useIntercom(...)' as it is undefined.

### ISSUE THREAD

**Issue by zeitvertrieb** [devrnt/react-use-intercom#416]
I implemented react-use-intercom in a gatsbyjs page as in your example.
on build I get this error:

WebpackError: TypeError: Cannot destructure property 'show' of 'useIntercom(...)' as it is undefined.

In my page component I use:

```
import { useIntercom } from "react-use-intercom";
const Contact: React.FC<PageProps> = () => {
  const { show } = useIntercom();
  return ( <button type="button" onClick={() => show()}>Chat</button> )
}
```

any ideas? thanks

**Comment by devrnt** [comment]
Please use the issue template or supply a reproduction

**Comment by jamiefrew** [comment]
Did you find a solution to this? having the same issue :(

**Comment by zomars** [comment]
We're having this issue on a next.js app:

 ```
TypeError: Cannot destructure property 'boot' of '(0 , react_use_intercom__WEBPACK_IMPORTED_MODULE_2__.useIntercom)(...)' as it is undefined.
 ```

**Comment by zomars** [comment]
Solved by doing to prevent rendering on SSG.

```js
import { useIntercom as _useIntercom } from "react-use-intercom";

const useIntercom =
  typeof window !== "undefined"
    ? _useIntercom
    : () => ({
        boot: () => {},
        show: () => {},
      });
```

And then using normally in my component.

**Comment by devrnt** [comment]
Thanks for the update @zomars. Small reminder that there is an [gatsby example available](https://github.com/devrnt/react-use-intercom/tree/master/examples/gatsby).

**Comment by zomars** [comment]
> Thanks for the update @zomars. Small reminder that there is an [gatsby example available](https://github.com/devrnt/react-use-intercom/tree/master/examples/gatsby).

we’re using Next in our case. And it fails at build by following the example exactly

**Comment by devrnt** [comment]
Can you provide a small reproduction, so I can take a look?

 [The nextjs example](https://github.com/devrnt/react-use-intercom/tree/master/examples/nextjs) works, so I'm interested what you did differently. Also in NextJS you can also [skip ssr](https://nextjs.org/docs/advanced-features/dynamic-import#with-no-ssr).

**Comment by zomars** [comment]
The main issue was using the latest version with react 17. Upgrading to React 18 made the error go away.

**Comment by devrnt** [comment]
I still don't see how that could be relevant, anyway I'm happy that's it has been resolved :)
