### ISSUE TITLE
browser "forward" breaks intercom

### ISSUE THREAD

**Issue by EdVilu** [devrnt/react-use-intercom#421]
**Describe the bug**
Using browsers "back" and "forward" buttons, while intercom is open, breaks the messenger

**To Reproduce**
1. Go to 'https://devrnt.github.io/react-use-intercom/#/'
2. Click on 'useIntercom'
3. Click on 'boot' and open the messenger
4. Click browser "back" while messenger is open
5. Click browser "forward"
6. Messenger breaks and leaves shadow outline

**Expected behavior**
Messenger works as intended

**Screenshots**
![image](https://user-images.githubusercontent.com/80050893/154694018-49370b02-794e-46b5-a697-ee82a1dfaede.png)

**Desktop:**
 - OS: windows
 - Browser: chrome
 - Version: 98.0.4758.82

**Comment by devrnt** [comment]
Thanks for reporting this issue. I can reproduce the same issue. I wonder what the cause is, I feel like it's specifically related to the playground setup

**Comment by EdVilu** [comment]
We first ran into this issue in our SPA that we are building. I just went to the playground to make sure that the issue isn't with just our setup and integration, so I don't think that the playground setup is at fault here.

**Comment by devrnt** [comment]
I tried reproducing this issue without this package (the "vanilla way") and it has the same issue. You can check out the [example that I used for reproduction](https://github.com/intercom/example-single-page-app-install). 

So I suggest creating a ticket in the [Intercom Forum](https://forum.intercom.com/s/), hope this helps you.

**Comment by JasonasIgn** [comment]
I followed @devrnt suggestion and created a [bug thread](https://forum.intercom.com/s/feed/0D55c000066ifuZCAQ) on the intercom forum. It seems like it got noticed by the dev team and got fixed, therefore this issue can be closed

**Comment by devrnt** [comment]
@JasonasIgn Thanks for following this up, really appreciate it!
