### ISSUE TITLE
APIBase not being respected

### ISSUE THREAD

**Issue by dannybrown** [devrnt/react-use-intercom#429]
All intercom projects in the EU have to set an `apiBase` so that they do not encounter a `region_mismatch` error.

I am using the following provider config:

```
<IntercomProvider
  appId={INTERCOM_APP_ID}
  apiBase="https://api-iam.eu.intercom.io"
>
```

However, all requests appear to go to `https://api-iam.intercom.io` still (NOTE: the lack of `.eu`) and so I get the `region_mismatch` error.

Version:
```
    "react-use-intercom": "1.5.0",
```

**Comment by devrnt** [comment]
Hi, thanks for creating this issue. Indeed seems like `api_base` (or `apiBase` in this package) is not taken into account.

As far as I see the `api_base` [should be set correctly](https://github.com/devrnt/react-use-intercom/blob/master/src/provider.tsx#L57). 

Could you open up your browsr DevTools console and enter `window.intercomSettings` and ensure `api_base` is set (when providing an `apiBase` to `<IntercomProvider>`?

**Comment by devrnt** [comment]
Closing this for now, feel free to re-open
