### ISSUE TITLE
Not working properly in staging

### ISSUE THREAD

**Issue by aldy97** [devrnt/react-use-intercom#476]
**Describe the bug**
Worked fine in local environment, but the intercom icon is not showing up in staging and also failed to send request to Intercom.
We are using `Hotjar`, and could this be the reason that why it fails? I am suspicious on that.

**To Reproduce**
Just happened on staging for testing purposes.

**Codesandbox link**
Include a codesandox will help us to investigate the issue quicker.

**Expected behavior**
The icon should pop up in the bottom right corner. And there should be a `ping` request sent to Intercom.
But none of them happened in the staging environment.

**Screenshots**
In local which works fine:
![image](https://user-images.githubusercontent.com/40585236/167964369-fa5457d3-23b2-48ff-a101-c129c9ee300a.png)

In staging which it fails:
![image](https://user-images.githubusercontent.com/40585236/167964140-8d81d48a-640b-4eb4-a75b-5e9e095e502c.png)

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser: chrome
 - Version: N/A

**Smartphone (please complete the following information):**

**Comment by devrnt** [comment]
Thanks for the extensive description, any updates on how this issue got resolved?

**Comment by BalloonalicsSoftware** [comment]
Oh hi @devrnt , thank you for the follow up. It turned out to be an issue with our CI/CD pipeline, so the deployment to staging failed.

Thank you again!

By the way, really good job! Already starred 👍

**Comment by Onbehalfofme** [comment]
@aldy97, I encountered the same issue, can you, please, share how to resolve this?
