### ISSUE TITLE
Provider complains about custom attributes

### ISSUE THREAD

**Issue by amcdnl** [devrnt/react-use-intercom#478]
## Issue
I use a plugin for Babel that annotates the React components ( https://github.com/fullstorydev/fullstory-babel-plugin-annotate-react ). When booting up, I get the following errors:

```
index.js:1 [react-use-intercom] some invalid props were passed to IntercomProvider. Please check following props: data-element, data-source-file.
```

Upon investigation, it looks like it complains about anything it doesn't know about in the `...rest` spread:

```
  if (!isEmptyObject(rest) && __DEV__)
    logger.log(
      'error',
      [
        'some invalid props were passed to IntercomProvider. ',
        `Please check following props: ${Object.keys(rest).join(', ')}.`,
      ].join(''),
    );
```

I feel like this should be loosened up to at minimal ignore `data-` attributes.

**Comment by amcdnl** [comment]
@devrnt - Happy to make a PR but... moving these to warnings will still flag my system so I'd prefer for it to ignore any `data-` attributes. Its pretty typical for things to be tagged using that for testing/etc.

**Comment by devrnt** [comment]
I see, ignoring the `data-x` attributes seems okay to me. Please add this extra check inside the `__DEV__` guard (see above)  so it has only impact on the dev bundle. If you would be so kind to submit a PR, then I'm eager to approve



By the way: out of interest what does FullStory do with the `data-x` attributes?

**Comment by amcdnl** [comment]
@devrnt - Take a look at: https://github.com/devrnt/react-use-intercom/pull/480

**Comment by amcdnl** [comment]
> By the way: out of interest what does FullStory do with the data-x attributes?

The custom attributes the plugin adds gives us the ability to define my explicit conditions for e2e and analytics. This plugin denotes all the components and their source for our team to identify root cause issues more easily.

**Comment by devrnt** [comment]
[v1.5.2](https://github.com/devrnt/react-use-intercom/releases/tag/v1.5.2)
