### ISSUE TITLE
Chat bot gets disappeared when passing email while booting

### ISSUE THREAD

**Issue by fdeliu** [devrnt/react-use-intercom#486]
Hi there,
When I boot the chat bot like this works fine:

![image](https://user-images.githubusercontent.com/43107323/170668702-0e1221a2-ff89-4994-a0aa-1a75c917995b.png)

But when I pass the email, the chat gets disappeared. Can you please help?

![image](https://user-images.githubusercontent.com/43107323/170668863-8a315f23-36e7-49a4-aaa8-3c83e838f586.png)

version: "react-use-intercom": "^1.5.2"

**Comment by devrnt** [comment]
This seems to be an issue on your end. Can you provide a reproduction link?

**Comment by fdeliu** [comment]
I can't sorry, is there any way you can help me with this please?
