### ISSUE TITLE
Ability to disable warnings in development

### ISSUE THREAD

**Issue by VladimirMikulic** [devrnt/react-use-intercom#523]
**Is your feature request related to a problem? Please describe.**

We don't initialize Intercom to anonymous users, only to logged in so in development `shouldInitialize` is pretty much `false` most of the time. However, that causes a few big blocks of warning on each page refresh.

![Screenshot_20220830_162027](https://user-images.githubusercontent.com/35997844/187462395-a3c4ca69-baa0-4260-b26f-d94a5684d7e9.png)

**Describe the solution you'd like**

I'd like to have ability to disable development warnings for this library given that we intentionally do it.
Not sure what's the best way to approach it - maybe separate prop?

**Describe alternatives you've considered**

N/A

**Additional context**

N/A

Thank you for making such a great library!

**Comment by VladimirMikulic** [comment]
Actually, nevermind, we found a different approach.
Thanks again!

**Comment by VladimirMikulic** [comment]
Given that we use Intercom only in production, we simply enabled domain whitelist and then we get simple one line warning from Intercom "domain not whitelisted".

**Comment by devrnt** [comment]
Thanks!
