### ISSUE TITLE
Ability to disable completely for a development environment

### ISSUE THREAD

**Issue by huksley** [devrnt/react-use-intercom#527]
**Is your feature request related to a problem? Please describe.**
So I have multiple environments (prod, dev, local) and I want so Intercom is only enabled only in some of them (based on environment settings which are available at compile time i.e. `process.env.USE_INTERCOM === "1"`)

**Describe the solution you'd like**
One option would be disabling at `IntercomProvider` level?
End effect should be NO intercom JS is fetched and all calls to boot() are ignored.
```jsx
<IntercomProvider disabled={true|false}>...</IntercomProvider>
```

**Describe alternatives you've considered**
Currently it is an awkward solution which breaks a rule of hooks, example:

```ts
export const useNoIntercom = () => {
  return {
    boot: () => {
      logger.info("Intercom disabled");
    }
  };
};

export const Page = ({user}:{user:User}) => {
  // eslint-disable-next-line react-hooks/rules-of-hooks
  const { boot } = process.env.NO_INTERCOM === "1" ? useNoIntercom() : useIntercom();
  useEffect(() => {
    boot({
      userId: user._id,
      name: user.name,
      email: user.email,
    })
  }, [user, boot])
}
```

**Comment by devrnt** [comment]
Hi, thanks for creating this issue. 

It seems like are looking for `shouldInitialize`, see https://github.com/devrnt/react-use-intercom#props

**Comment by huksley** [comment]
Yes, it works fine! How I missed it! Thank you!
