### ISSUE TITLE
Not removing focus of the button 

### ISSUE THREAD

**Issue by TiberioG** [devrnt/react-use-intercom#528]
**Describe the bug**
The button does not unfocus itself after the chat has been closed

**To Reproduce**
1. open intercom chat by clicking the button
2. close the chat by clicking the button
3. press barspace in our application
4. error: the intercom opens again since it was focused instead of our application page 

**Codesandbox link**

**Expected behavior**
intercom button should unfocus itself

**Additional info**
I used this snippet to hack it but it is not a long term solution
```const actionOnClose = () => {
  // this is needed to remove focus from the intercom button to avoid bugs like
  // When closing the chat and then pressing space to pan, space will actually open the chat again
const actionOnClose = () => {
  if (document.activeElement instanceof HTMLElement) {
    document.activeElement.blur();
  }
};

....
<IntercomProvider appId={INTERCOM_APP_ID} onShow={actionOnOpen} onHide={actionOnClose}>
```

**Desktop (please complete the following information):**
 - OS:macos
 - Browser Chrome
 - Version 104.0.5112.101 (Official Build) (arm64)

**Comment by devrnt** [comment]
Seems not related to this library. You can try reporting it on https://forum.intercom.com/s/
