### ISSUE TITLE
noisy

### ISSUE THREAD

**Issue by schester44** [devrnt/react-use-intercom#534]
**Describe the bug**
This lib is very noisy when running tests within jest. It outputs a ton of console.logs

**To Reproduce**
Use it in jest with shouldInitialize set to false.

**Expected behavior**
eliminate the logs or provide a prop to not log to console

**Screenshots**
<img width="1032" alt="Screen Shot 2022-09-13 at 8 52 56 AM" src="https://user-images.githubusercontent.com/15207595/189906382-57700b21-e27d-427c-b1a9-f243381c91d5.png">

**Comment by devrnt** [comment]
This is expected behavior and I plan to keep this functionality. I suggest running your test environment against the production bundles of your external modules
