### ISSUE TITLE
Integrating Product Tours

### ISSUE THREAD

**Issue by aldy97** [devrnt/react-use-intercom#538]
**Describe the bug**
Trying to start a product tours using Intercom but it says the messenger is not installed.
![image](https://user-images.githubusercontent.com/40585236/191267592-130bac27-420c-4166-827f-046c020e9d8c.png)

**To Reproduce**
1. Go to Intercom dashboard
2. Go to`Outbound` and then `tour`
3. Click on `Step One`
4. Fill in the website url that has installed Intercom messenger using `react-use-intercom`

**My Guess**:
![image](https://user-images.githubusercontent.com/40585236/191268357-dabca318-a13e-4ed2-8888-2d195ef1ebe9.png)

![image](https://user-images.githubusercontent.com/40585236/191268573-72cf3a45-03d5-4e27-8211-44a55453d9ba.png)

**Comment by devrnt** [comment]
Hi, this is weird. There is a working example in the [playground](https://github.com/devrnt/react-use-intercom/blob/master/playground/modules/useIntercom/useIntercomTour.tsx), see [demo](https://devrnt.github.io/react-use-intercom/#/useIntercomTour). 

Are you sure everything is [setup correctly](https://www.intercom.com/help/en/articles/2900887-design-your-product-tour) in the Intercom dashboard?

**Comment by aldy97** [comment]
Hey Jonas, thanks for your prompt response! Also thank you for the links provided. I am so happy that you have product tour handled so well in this lib. 
My guess is that I did not setup correctly. I will investigate further. 

Thank you again. 👍

**Comment by aldy97** [comment]
Oh this question might seem to be irrelevant but thought you'd just be able to help me with that, if this is the whole complete url that integrates Intercom in it. 
![image](https://user-images.githubusercontent.com/40585236/191338946-244e402a-f5a9-47af-b424-ce7f9e67a849.png)
Should I just use that or the root url without `/user/home` in this case?

Great thanks!

**Comment by TristanWYL** [comment]
Hi @devrnt , it seems that the `start tour` in this [demo](https://devrnt.github.io/react-use-intercom/#/useIntercomTour) is broken. I click on the btn and nothing is shown.

**Comment by devrnt** [comment]
> Hi @devrnt , it seems that the `start tour` in this [demo](https://devrnt.github.io/react-use-intercom/#/useIntercomTour) is broken. I click on the btn and nothing is shown.

Indeed, having the same problem. It still works via the preview in the Intercom dashboard. I'll have to reach out to the Intercom support.

**Comment by devrnt** [comment]
> > Hi @devrnt , it seems that the `start tour` in this [demo](https://devrnt.github.io/react-use-intercom/#/useIntercomTour) is broken. I click on the btn and nothing is shown.
> 
> Indeed, having the same problem. It still works via the preview in the Intercom dashboard. I'll have to reach out to the Intercom support.

Has been resolved. One of the steps was pointing to a nonexisting element in the DOM
