### ISSUE TITLE
How to Retrive Posted Data in Intercom 

### ISSUE THREAD

**Issue by RakulAgn** [devrnt/react-use-intercom#539]
I Like to Retrive Data which i posted while on boot and now i need to retrive data from intercom is there any options are there ?

**Comment by devrnt** [comment]
Hi, please use the issue template.

All data is available in `window.intercomSettings`

**Comment by RakulAgn** [comment]
Thanks

**Comment by RakulAgn** [comment]
Hey . is that Boot Method Return Response. ?
