### ISSUE TITLE
Decrease bundle size of npm package?

### ISSUE THREAD

**Issue by multivoltage** [devrnt/react-use-intercom#541]
I noticed you put "src" in "files" inside package.json.
What the reason to do that? Can I do a pull request to remove that or you put for some specific reason?
Thanks

**Comment by devrnt** [comment]
Thanks for creating this issue. 

I will keep the source code in the published module. It's useful for introspection and I prefer to have both the production- as source code in the published module.

**Comment by devrnt** [comment]
> Thanks for creating this issue.
> 
> I will keep the source code in the published module. It's useful for introspection and I prefer to have both the production- as source code in the published module.

Coming back to this, I've removed the `src` folder in the published package. Published in release [v.1.5.1](https://github.com/devrnt/react-use-intercom/releases/tag/react-use-intercom%405.1.1)
