### ISSUE TITLE
Noisy

### ISSUE THREAD

**Issue by schester44** [devrnt/react-use-intercom#544]
This is a very noisy package when testing components while `shouldInitialize` is set to false. It would be awesome if there was an easy and straightforward way to suppress the following error.

```
[react-use-intercom] Intercom instance is not initialized because `shouldInitialize` is set to `false` in `IntercomProvider`
```

**Comment by devrnt** [comment]
See https://github.com/devrnt/react-use-intercom/issues/523

**Comment by schester44** [comment]
We were seeing a new set of errors in vitest when removing `shouldInitialize={false}`. I ended up fixing this issue by mocking `window.Intercom` and keeping `shouldInitialize={false}`.


```
global.Intercom = vi.fn()

<Provider shouldInitialize={false} />
```
