### ISSUE TITLE
README Typo `are these`

### ISSUE THREAD

**Issue by grempe** [devrnt/react-use-intercom#546]
There is a typo (transposed words) in this section of the README:

https://github.com/devrnt/react-use-intercom#intercomprops

Change:

```
 in react-use-intercom are these camel cased.
```

to

```
 in react-use-intercom these are camel cased.
```

**Comment by devrnt** [comment]
Thanks for reporting this issue. Would like you to pick this up and open a pull request?

**Comment by devrnt** [comment]
Fixed
