### ISSUE TITLE
Should be able to call boot more than once

### ISSUE THREAD

**Issue by nathanjcochran** [devrnt/react-use-intercom#555]
**Is your feature request related to a problem? Please describe.**

Currently, the `boot` method can only be called once. Subsequent calls are no-ops, due to this [isBooted check](https://github.com/devrnt/react-use-intercom/blob/23dcbc8ecb6cd3f80eb2560d6bd0b6a89952e846/src/provider.tsx#L61-L63).

However, the [Integrate Intercom in a single page app](https://www.intercom.com/help/en/articles/170-integrate-intercom-in-a-single-page-app) documentation describes a process whereby you call boot once for logged out users, and again later once they've logged in:

> An example of this for logged out visitors would be:
> 
> ```
> window.Intercom('boot', {
>    app_id: 'abc12345',
>    custom_launcher_selector: '#my_custom_link' 
> });
> ```
> 
> **Important**: If you copy the code snippet above make sure to manually change your [workspace ID](https://docs.intercom.com/faqs-and-troubleshooting/getting-set-up/where-can-i-find-my-workspace-id-app-id) (this is called your APP_ID in the code). 
> 
> Then, when you'd like to log them in or convert them to a user, simply change the boot method to include their user info:
> 
> ```
> window.Intercom('boot', {
>    app_id: 'abc12345',
>    email: 'example@example.com',
>    user_id: 'abc123',
>    created_at: 1234567890,
>    custom_launcher_selector: '#my_custom_link' 
> });
> ```

Following this process makes it so that any conversations started when the user was logged out are merged with the user's pre-existing conversations when they log in.

**Describe the solution you'd like**

I think it should be possible to call `boot` more than once. I would recommend just removing [this check](https://github.com/devrnt/react-use-intercom/blob/23dcbc8ecb6cd3f80eb2560d6bd0b6a89952e846/src/provider.tsx#L61-L63). Alternatively, you could create a separate method (e.g. `reboot`? `hardBoot`?) that doesn't have that check.

**Describe alternatives you've considered**

I tried calling `update` when the user logs in, but it does not have the same effect (the user's pre-existing conversations do not appear when they log in). I also tried calling `shutdown` and then calling `boot` again, but that does not work right either (the conversations started when the user was logged out are never associated with their account, and are essentially gone forever).

**Comment by nathanjcochran** [comment]
Nevermind. I was ultimately able to get this working by calling `boot` once (via `autoBoot`), and then calling `update` subsequently when the user logs in. Not sure why it wasn't fetching the user's pre-existing conversations before - perhaps it was just Intercom itself being slow/buggy 🤷.

**Comment by devrnt** [comment]
Thanks for creating this issue. It's really helpful to give such a detailed description. 
 
It also makes more sense to me to remove the guard. This leans more towards the one-on-one abstraction of the "vanilla" module that this library tends to be.

I'll probably come back to this in the near feature
