### ISSUE TITLE
Disable launcher

### ISSUE THREAD

**Issue by ritute** [devrnt/react-use-intercom#620]
**Is your feature request related to a problem? Please describe.**
We're using intercom only for displaying banners in our app. Even though we have hideDefaultLauncher set to true in boot properties, we noticed the chat FAB still appears at random times (unable to reproduce it). Our current hack is to position it off the screen with horizontal and vertical padding properties.

**Describe the solution you'd like**
We're not sure why the hideDefaultLauncher isn't obeyed at all times. Can we have a way to disable this launcher altogether?

**Describe alternatives you've considered**
 Positioning it off the screen with horizontal and vertical padding properties.

**Additional context**

**Comment by devrnt** [comment]
According to the [IntercomJS docs](https://developers.intercom.com/installing-intercom/docs/javascript-api-attributes-objects#messenger-attributes) (`hide_default_launcher`) this should be working, if not please report it on the IntercomJS forum.

Have you checked https://www.intercom.com/help/en/articles/189-hide-the-intercom-messenger-launcher?

**Comment by devrnt** [comment]
Feel free to re-open
