### ISSUE TITLE
NextJS 13 reading properties of undefined

### ISSUE THREAD

**Issue by ricardo-fnd** [devrnt/react-use-intercom#633]
**Describe the bug**
Using 'use client' on Next13 to render IntercomProvider throws an error at `react-use-intercom/dist/index.mjs (3:1466)`

**To Reproduce**
1. Create a new file to wrap the context (assuming react-use-intercom is not using 'use client' directive) (https://beta.nextjs.org/docs/rendering/server-and-client-components#using-context-in-client-components)
2. Render your new Provider inside layout.jsx
3. Run the dev server

**Screenshots**
<img width="1073" alt="Screenshot 2023-03-27 at 17 14 15" src="https://user-images.githubusercontent.com/52207061/228000970-0cc0d06a-1821-4476-b978-adb3458e0855.png">

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser chrome

**Additional context**
I'm assuming that this error is because integration with NextJS 13 wasn't made.

**Comment by devrnt** [comment]
Hi, have you checked https://beta.nextjs.org/docs/rendering/server-and-client-components#rendering-third-party-context-providers-in-server-components?

**Comment by devrnt** [comment]
Hi, I tried reproducing the issue but I couldn't reproduce your issue. Can you provide a minimal reproduction?

**Comment by ricardo-fnd** [comment]
Ok! @devrnt the problem is that `Layout.jsx` is a ASYNC react server component. 
If I remove the `async` from the `Layout.jsx` component, it works. Though, I need this to be async... Any suggestion?

![Screenshot 2023-03-30 at 16 26 33](https://user-images.githubusercontent.com/52207061/228886203-e7b831c5-97c4-47dd-b4f8-3e51f15e0a3e.png)

**Comment by pago** [comment]
In case somebody else stumbles upon this issue as well and needs a workaround:
The problem seems to be that Intercom doesn't find a `script` tag after which it can insert its own script. Thus, a workaround is to add `script` tag to the document.

```jsx
<Script id="intercom-setup-help">{` `}</Script>
```

Adding the above as a sibling before the `IntercomProvider` solved the issue for me.

**Comment by cordial** [comment]
> ```js
> ```js
> <Script id="intercom-setup-help">{` `}</Script>
> ```
> 
> 
>     
>       
>     
> 
>       
>     
> 
>     
>   
> ```

can you give a more complete workaround?
