### ISSUE TITLE
Use lower node version to prevent npm claims about node < 18

### ISSUE THREAD

**Issue by eaglus** [devrnt/react-use-intercom#638]
Why node version 16 is too old to install react-use-intercom?
I think, we should remove { node: '>=18' } requirement or make node version lower at least to 14

```
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'react-use-intercom@5.0.0',
npm WARN EBADENGINE   required: { node: '>=18' },
npm WARN EBADENGINE   current: { node: 'v16.19.1', npm: '8.19.3' }
npm WARN EBADENGINE }

```

**Comment by devrnt** [comment]
Thanks for creating this issue. I don't consider this to be an issue. Notice that the log is just a warning and is not breaking anything (except if you pass `--engine-strict`). I want to keep track of the Node LTS version (which is 18 at this moment).

**Comment by devrnt** [comment]
Thanks for coming back to this @JamieDixon. I've reproduced this and indeed `yarn` does throw an error, thanks for pointing this out.
 I'll just remove the `engine` entry since it's useless anyway in user-land

**Comment by devrnt** [comment]
[v1.5.4](https://github.com/devrnt/react-use-intercom/releases/tag/react-use-intercom%405.1.4)
