### ISSUE TITLE
Use apiBase for regional data hosting?

### ISSUE THREAD

**Issue by timonbimon** [devrnt/react-use-intercom#653]
**Describe the bug**
Not sure if it's still a bug, but rather wanted to clarify whether it's possible to use the api_base correctly with `react-use-intercom` before I start trying to use the library?

https://github.com/devrnt/react-use-intercom/pull/96#issuecomment-1377103945

there are two comments on this MR that sound like others that wanted to use "https://api-iam.eu.intercom.io" but it didn't work for them and they ended up not using this library?

**Comment by devrnt** [comment]
Please don't create an issue with a question. This module is still working as expected. If the underlying functionality is not working please ask this to the Intercom support.

See https://developers.intercom.com/installing-intercom/docs/basic-javascript

**Comment by timonbimon** [comment]
ok, thanks for the quick reply! for future reference (and others that might be reading along): where would you prefer that people ask questions instead of here? :)

**Comment by devrnt** [comment]
Prefer using "Q&A" in Discussions
