### ISSUE TITLE
Don't load intercom in some pages?

### ISSUE THREAD

**Issue by imclint21** [devrnt/react-use-intercom#657]
Hi,

is it possible to don't boot intercom on some pages?

I tried somethings like this:

```tsx
const forbiddenUrls = ["/purchases/create", "/products"];
return (
<IntercomProvider
  appId={INTERCOM_APP_ID}
  autoBoot
  shouldInitialize={!forbiddenUrls.includes(pathname)}>
  {children}
</IntercomProvider>
)
```

But it does not seems to work.

Regards

**Comment by nicolasacquaviva** [comment]
Hey @imclint21, I didn't want to load the intercom scripts in certain pages and to do so I did something very similar to your example and it is working the only difference is that I'm not using the `autoBoot` prop

**Comment by imclint21** [comment]
> Hey @imclint21, I didn't want to load the intercom scripts in certain pages and to do so I did something very similar to your example and it is working the only difference is that I'm not using the `autoBoot` prop

Yes so you have to manually boot in each page no?

**Comment by nicolasacquaviva** [comment]
> > Hey @imclint21, I didn't want to load the intercom scripts in certain pages and to do so I did something very similar to your example and it is working the only difference is that I'm not using the `autoBoot` prop
> 
> Yes so you have to manually boot in each page no?

Yes, that's what I'm doing. I have a wrapper component in charge of doing the boot and I'm wrapping with it the pages where I want the script to load

**Comment by imclint21** [comment]
Any idea @devrnt ?

**Comment by devrnt** [comment]
Please provide a reproduction so I can take a look

**Comment by imclint21** [comment]
Unfortunately I'll not have time, maybe I could help you tu understand what I want to achieve?

**Comment by devrnt** [comment]
See solution from @nacq https://github.com/devrnt/react-use-intercom/issues/657#issuecomment-1717718938
