### ISSUE TITLE
Support for custom_launcher_selector in IntercomProvider

### ISSUE THREAD

**Issue by charitha-work** [devrnt/react-use-intercom#659]
As a developer I would like to pass a class/id as a custom selector so that I can customize it's style from my react code.

eg: `<IntercomProvider appId="appId" customLauncherSelector="my-selector">{children}</IntercomProvider>`

For the moment I selected .intercom-messenger-frame in a css file and styled as I wanted.

**Comment by devrnt** [comment]
Please check the docs first before creating an issue.

Since I'm here: you can already pass `customLauncherSelector` to the `boot` method. If `autoBoot` is used, you can set the same option in `autoBootProps`
