### ISSUE TITLE
[Intercom] Launcher is disabled in settings or current page does not match display conditions

### ISSUE THREAD

**Issue by adiathasan** [devrnt/react-use-intercom#665]
**Describe the bug**
When I open a webgl context. the intercom vanishes. And later it prints the following message in the console.

" [Intercom] Launcher is disabled in settings or current page does not match display conditions "

**To Reproduce**
1. Open a webgl context 
2. That's it!

**Expected behavior**
Should not be vanishing

**Desktop (please complete the following information):**
 - OS: [Mac OS]
 - Browser [chrome, firefox]

**Comment by TaylorFoster-Informulate** [comment]
@adiathasan how did you resolve this? Running into the same issue.

**Comment by drlube** [comment]
I am seeing the same issue intermittently in our web app that embeds intercom.

Getting a 400 Bad Request returned from https://api-iam.intercom.io/messenger/web/ping
