### ISSUE TITLE
using useIntercom hook makes every event perform a rerender

### ISSUE THREAD

**Issue by fakhribenfraj** [devrnt/react-use-intercom#667]
**Describe the bug**
when i use the hook (boot or update), if we click on the chat button, the app performs a rerender, when i close the chat, it performs a rerender

**To Reproduce**
just call useIntercom hook then open and close the chat

**Expected behavior**
opening and closing the chat shoudn't perform a rereder since i am only calling the boot function

**Additional context**
i am using react 17.0.2

**Comment by devrnt** [comment]
Thanks for creating this issue.

This is expected behaviour since [v2.1.0](https://github.com/devrnt/react-use-intercom/releases/tag/v2.1.0). In this version the `isOpen` flag was introduced which returns the visibility status of the messenger

**Comment by ralphholzmann** [comment]
@fakhribenfraj I'm running into this same issue right now -- were you able to get around it somehow? We have a bunch of user state that is getting reset the instant they open intercom.
