### ISSUE TITLE
Allow setting of `region` parameter

### ISSUE THREAD

**Issue by felixhagspiel** [devrnt/react-use-intercom#674]
**Is your feature request related to a problem? Please describe.**
There is no `region` parameter as there is in the plain JS SDK: https://developers.intercom.com/installing-intercom/web/installation/#basic-javascript

**Describe the solution you'd like**
I want to be able to set the region to `eu`

**Describe alternatives you've considered**
I guess setting the API base to `https://api-iam.eu.intercom.io` should solve it, but not sure if there is more going on behind the scenes when setting the `region` parameter.

**Additional context**
This might be related: https://github.com/devrnt/react-use-intercom/issues/429

**Comment by devrnt** [comment]
I don't see a `region` parameter in the official docs, can you point me towards it? I assume you are trying to set the underlying `api_base`, if so you can already do this by setting the `apiBase` in the  `IntercomProvider`.

If you have any questions, let me know!

**Comment by felixhagspiel** [comment]
hey @devrnt I see them in the typescript type of the messenger
<img width="483" alt="image" src="https://github.com/devrnt/react-use-intercom/assets/5927172/7e815a23-fc9b-4161-8212-eb6bcebf3eb9">
But could also just be a shorthand for the `apiBase`

**Comment by devrnt** [comment]
Seems like you are referring to [another library](https://www.npmjs.com/package/@intercom/messenger-js-sdk).

`react-use-intercom` is an unofficial library and has nothing to do with the official library

**Comment by felixhagspiel** [comment]
sorry, cant believe I have missed that :) thank you for looking into that.
