### ISSUE TITLE
Uncaught TypeError: Cannot read properties of null (reading 'instantBootEnabled')

### ISSUE THREAD

**Issue by the-phoenix** [devrnt/react-use-intercom#680]
While using intercom on my react project. I can see this error.
Uncaught TypeError: Cannot read properties of null (reading 'instantBootEnabled')
I'm not sure It caused suddenly. It worked till now.

Here is my code:
```
const { boot } = useIntercom();
useEffect(() => {
  boot({
    customAttributes: {
      horizontal_padding: 25,
    },
  });
}, [boot]);
```

**Comment by AaronPowell96** [comment]
This has just started occurring for us over the past couple of days too, unaware of any code changes our side that caused this.

**Comment by anibe** [comment]
I was getting this earlier but now seems to have fixed itself. The exception originated from `https://js.intercomcdn.com/frame-modern.xxx.js` so perhaps it was a wider problem with Intercom rather than this library.

**Comment by jose-mdz** [comment]
Same problem

**Comment by theseyi** [comment]
Also seeing this intermittently under local development

**Comment by jannikbertram** [comment]
This seems to be crashing how web app quite frequently. Here is a full stacktrace

```
{
  message: null is not an object (evaluating 'e.instantBootEnabled'),
  name: TypeError,
  stack: 
@https://js.intercomcdn.com/frame.9a0e43ba.js:2:657609
v@https://js.intercomcdn.com/vendor.989ae25f.js:2:535589
@https://js.intercomcdn.com/vendor.989ae25f.js:2:537066
v@https://js.intercomcdn.com/vendor.989ae25f.js:2:535589
@https://js.intercomcdn.com/vendor.989ae25f.js:2:537032
v@https://js.intercomcdn.com/vendor.989ae25f.js:2:535589
@https://js.intercomcdn.com/frame.9a0e43ba.js:2:659107
@https://js.intercomcdn.com/vendor.989ae25f.js:2:584026
forEach@[native code]
m@https://js.intercomcdn.com/vendor.989ae25f.js:2:584019
dispatch@https://js.intercomcdn.com/vendor.989ae25f.js:2:550272
@https://js.intercomcdn.com/frame.9a0e43ba.js:2:609920
@https://js.intercomcdn.com/frame.9a0e43ba.js:2:565249
@https://js.intercomcdn.com/frame.9a0e43ba.js:2:563866
@https://js.intercomcdn.com/frame.9a0e43ba.js:2:558823
@https://js.intercomcdn.com/frame.9a0e43ba.js:2:566465
@https://js.intercomcdn.com/vendor.989ae25f.js:2:561681
@https://js.intercomcdn.com/frame.9a0e43ba.js:2:632589
@https://js.intercomcdn.com/frame.9a0e43ba.js:2:671283
shutdown@https://js.intercomcdn.com/frame.9a0e43ba.js:2:690621
@https://<our-web-app>/_next/static/chunks/pages/_app-4f5322db7c0bcefe.js:65:2362803
[...]
}
```

**Comment by lieberkind** [comment]
We're also seeing this error in Sentry, but we're not using `react-use-intercom`, adding to @anibe's point that this might be related to Intercom itself. We're still seeing the errors though.

**Comment by yonitou** [comment]
Same issue !

**Comment by cookpete** [comment]
We ended up wrapping the `boot()` call with a `try/catch` – not ideal, but seems to have stopped it from crashing our entire app.

**Comment by jannikbertram** [comment]
> We ended up wrapping the `boot()` call with a `try/catch` – not ideal, but seems to have stopped it from crashing our entire app.

We did the same. @cookpete do you know what happens if `boot()` fails. Is Intercom just not showing in that session? And does it work again when refreshing the page?

**Comment by cookpete** [comment]
When `boot()` caused an `instantBootEnabled` error it would get caught by our `ErrorBoundary` and show our error page, preventing users from using the app. Although they could still open the Sentry report dialog to report the problem. Sentry showed the `instantBootEnabled` trace but Fullstory just showed a console error of `{}`, which is a bit confusing.

This only happened for a small number of users and we couldn’t see any patterns or clues as to why it happens.

**Comment by theseyi** [comment]
@anibe do you have a link to the support request?

**Comment by anibe** [comment]
@theseyi no link as it was an internal request.

They have come back to say the issue has been fixed, hopefully it should be fixed for everyone here too 🤞 

![image](https://github.com/user-attachments/assets/09df120b-e511-42aa-b34f-1995fefbed1a)

**Comment by devrnt** [comment]
I'm happy to hear that Intercom resolved the issue Thanks for the updates!
