### ISSUE TITLE
Strange console logs

### ISSUE THREAD

**Issue by tristanhcole** [devrnt/react-use-intercom#77]
**Describe the bug**
Console log prints html elements and `isElementCoveringWebui`. Wondering if this is caused by react-use-intercom, we recently integrated and seems to have just started occurring.

<img width="407" alt="Screen Shot 2020-08-13 at 4 41 03 pm" src="https://user-images.githubusercontent.com/27039316/90102559-3dc58d80-dd84-11ea-9ec7-bd0619fcaa32.png">

Great work on the package @devrnt! Super easy to integrate ⚡

**Comment by devrnt** [comment]
Thanks for reporting, but this issue is not related to `react-use-intercom`. This seems a problem in the Google Chrome Dashline extension. 

A quick Google search: https://stackoverflow.com/questions/60654059/google-chrome-extension-kwift-chrome-min-js
