### ISSUE TITLE
TypeError: Object(...) is not a function

### ISSUE THREAD

**Issue by jovanimal** [devrnt/react-use-intercom#99]
**Describe the bug**
I've installed react-use-intercom in several modules that I previously worked on but this time, it throws such error when I try to to insert `<IntercomProvider>` in the highest level. I'm wondering if it has anything to do with other dependencies.

![image](https://user-images.githubusercontent.com/54385240/94761598-0bc1c680-03d8-11eb-91e2-8cf8e07f4bf2.png)

**Additional context**
My installation code (hide appId for privacy purpose)
![image](https://user-images.githubusercontent.com/54385240/94761812-96a2c100-03d8-11eb-9ca3-d07d5ac6bcaf.png)

My package.json

![image](https://user-images.githubusercontent.com/54385240/94761657-2a27c200-03d8-11eb-9bc2-fb84f3d56315.png)

**Comment by devrnt** [comment]
Thanks for your report.

 `react-use-intercom` makes use of hooks internally, these were introduced in React `16.8.0`. Since your React version is `16.6.3` it won't work, that's why we add `"react": ">=16.8.0",` in this packages its `peerDependencies`.

**Comment by jovanimal** [comment]
@devrnt It works fine after I updated `react` to latest version which is 16.13.1! 

I didn't think it was because of `react` version in the first place because I'd successfully installed Intercom in another module which has the version `16.6.3` using `react-use-intercom`.

The `package.json` file from another module.
![image](https://user-images.githubusercontent.com/54385240/94791642-87d50200-040a-11eb-8fa7-4ba9e96df290.png)

**Comment by devrnt** [comment]
Seems strange, I've no explanation for that. Maybe you have a local package link for `react`.
